export const suggestions = [
  'Hey, how are you doing today?',
  'I really liked your recent post!',
  'Do you have any book recommendations?',
  "What's your favorite movie of all time?",
  'You inspire me every day!',
  'Where do you find your motivation?',
  'Have you ever traveled abroad?',
  "What's your hidden talent?",
  'If you could meet anyone, who would it be?',
  'You have a great smile!',
  'Keep pushing forward, you got this!',
  "What's your favorite book?",
  'Do you play any musical instruments?',
  "What's the best gift you've ever received?",
  "What's the biggest challenge you've overcome?",
  "Who's your role model?",
  "What's your dream job?",
  "You're amazing at what you do!",
  'Do you have any pets?',
  'Never stop believing in yourself!',
  'You have a wonderful sense of humor!',
  'I admire your dedication!',
  "What's your favorite hobby?",
  "Where's your favorite place to relax?",
  'What’s your favorite quote?',
  "What's the best piece of advice you've ever received?",
  "What's your favorite way to spend a weekend?",
  'If you could visit any place in the world, where would you go?',
  "What's your favorite season and why?",
  'What’s your favorite type of music?',
  'Do you have a favorite song?',
  "What's the most memorable experience you've had?",
  'Do you have a favorite holiday tradition?',
  "What's your favorite type of food?",
  'Do you have a favorite restaurant?',
  "What's your favorite thing to cook or bake?",
  "What's your favorite childhood memory?",
  "What's your favorite way to unwind after a long day?",
  'Do you have a favorite sports team?',
  'What’s your favorite sport to play or watch?',
  'Do you enjoy any outdoor activities?',
  "What's your favorite indoor activity?",
  'What’s your favorite board game or card game?',
  'Do you enjoy puzzles or brainteasers?',
  'What’s your favorite TV show?',
  'Do you have a favorite actor or actress?',
  "What's your favorite type of movie?",
  'What’s the best movie you’ve seen recently?',
  'Do you enjoy reading fiction or non-fiction?',
  "What's your favorite subject to learn about?",
  'Do you have a favorite podcast?',
  "What's your favorite way to stay active?",
  'What’s your favorite app or website?',
  'Do you have a favorite social media platform?',
  'What’s your favorite way to connect with friends?',
  "What's your favorite memory from high school?",
  'What’s your favorite thing about your hometown?',
  'Do you have a favorite travel destination?',
  "What's your favorite way to spend time with family?",
  'What’s your favorite way to spend time with friends?',
  "What's your favorite thing about your job or school?",
  'Do you have a favorite book genre?',
  'What’s your favorite holiday?',
  'What’s your favorite thing to do on a rainy day?',
  'Do you have a favorite flower or plant?',
  'What’s your favorite thing about nature?',
  'What’s your favorite animal?',
  'Do you have a favorite zoo or aquarium?',
  'What’s your favorite historical period?',
  'Do you have a favorite artist or artwork?',
  'What’s your favorite museum?',
  "What's your favorite way to volunteer or give back to the community?",
  'Do you have a favorite charity or cause?',
  'What’s your favorite thing about your culture or heritage?',
  'What’s your favorite thing to do on a sunny day?',
  'Do you have a favorite type of weather?',
  'What’s your favorite thing about your personality?',
  'What’s your favorite childhood toy?',
  'Do you have a favorite superhero or fictional character?',
  'What’s your favorite thing about being an adult?',
  'What’s your favorite piece of technology?',
  'Do you have a favorite gadget or tool?',
  'What’s your favorite thing to do when you’re feeling creative?',
  'What’s your favorite memory from college or university?',
  'Do you have a favorite professor or teacher?',
  'What’s your favorite way to celebrate your birthday?',
  'Do you have a favorite holiday tradition?',
  'What’s your favorite family tradition?',
  'What’s your favorite way to relax?',
  'Do you have a favorite spa or wellness routine?',
  'What’s your favorite way to practice self-care?',
  'Do you have a favorite meditation or mindfulness practice?',
  'What’s your favorite thing to do on vacation?',
  'What’s your favorite way to explore a new city?',
  'Do you have a favorite road trip destination?',
  'What’s your favorite thing about yourself?',
  'What’s your favorite way to start your day?',
  'Do you have a favorite morning routine?',
  'What’s your favorite way to end your day?',
  'What’s your favorite nighttime routine?',
  'What’s your favorite inspirational quote?',
];
